#!/usr/bin/env bash
#
# install-zsh.sh — Self-contained zsh + plugins + starship setup for WSL.
#
# Single file: clones nothing of its own — config is written inline below.
# Installs: zsh, git, curl, starship
# Plugins (cloned to ~/.zsh/plugins, sourced from ~/.zshrc):
#   - zsh-completions            (fpath only, NOT sourced)
#   - zsh-autosuggestions
#   - zsh-you-should-use
#   - zsh-syntax-highlighting
#   - zsh-history-substring-search
#
# Idempotent: re-running updates plugins and rewrites config (existing
# ~/.zshrc / ~/.config/starship.toml are backed up first).
#
# Usage:
#   chmod +x install-zsh.sh && ./install-zsh.sh

set -euo pipefail

# ---- helpers ---------------------------------------------------------------
c_info()  { printf '\033[1;34m::\033[0m %s\n' "$*"; }
c_ok()    { printf '\033[1;32mok\033[0m %s\n' "$*"; }
c_warn()  { printf '\033[1;33m!!\033[0m %s\n' "$*"; }
die()     { printf '\033[1;31mxx\033[0m %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] && die "Run as a normal user, not root (the script uses sudo where needed)."

SUDO=""
command -v sudo >/dev/null 2>&1 && SUDO="sudo"

PLUGIN_DIR="${HOME}/.zsh/plugins"

# ---- 1. system packages ----------------------------------------------------
command -v apt-get >/dev/null 2>&1 \
  || die "This script targets Debian/Ubuntu WSL (apt-get not found)."

c_info "Updating package lists & installing base packages..."
$SUDO apt-get update -y
$SUDO apt-get install -y zsh git curl
c_ok "zsh, git, curl installed."

# eza: modern, colourful `ls` replacement. Optional — if apt doesn't carry it
# (older Ubuntu/Debian), we silently fall back to coloured coreutils `ls`.
if command -v eza >/dev/null 2>&1; then
  c_ok "eza already installed."
elif $SUDO apt-get install -y eza >/dev/null 2>&1; then
  c_ok "eza installed."
else
  c_warn "eza not available via apt — ls aliases will use coreutils 'ls --color'."
fi

# ---- 2. starship -----------------------------------------------------------
if command -v starship >/dev/null 2>&1; then
  c_ok "starship already installed ($(starship --version | head -n1))."
else
  c_info "Installing starship prompt..."
  curl -fsSL https://starship.rs/install.sh | $SUDO sh -s -- --yes
  c_ok "starship installed."
fi

# ---- 3. plugins ------------------------------------------------------------
declare -A PLUGINS=(
  [zsh-completions]="https://github.com/zsh-users/zsh-completions"
  [zsh-autosuggestions]="https://github.com/zsh-users/zsh-autosuggestions"
  [zsh-you-should-use]="https://github.com/MichaelAquilina/zsh-you-should-use"
  [zsh-syntax-highlighting]="https://github.com/zsh-users/zsh-syntax-highlighting"
  [zsh-history-substring-search]="https://github.com/zsh-users/zsh-history-substring-search"
)

mkdir -p "$PLUGIN_DIR"
for name in "${!PLUGINS[@]}"; do
  dest="${PLUGIN_DIR}/${name}"
  if [ -d "${dest}/.git" ]; then
    c_info "Updating ${name}..."
    git -C "$dest" pull --ff-only --quiet || c_warn "Could not update ${name}, keeping existing copy."
  else
    c_info "Cloning ${name}..."
    git clone --depth=1 --quiet "${PLUGINS[$name]}" "$dest"
  fi
done
c_ok "Plugins ready in ${PLUGIN_DIR}."

# ---- 4. config files (written inline) --------------------------------------
ts="$(date +%Y%m%d-%H%M%S)"

backup() {
  local dst="$1"
  if [ -f "$dst" ]; then
    cp "$dst" "${dst}.bak.${ts}"
    c_warn "Backed up existing $(basename "$dst") -> ${dst}.bak.${ts}"
  fi
}

# --- ~/.zshrc ---
backup "${HOME}/.zshrc"
cat > "${HOME}/.zshrc" <<'ZSHRC'
# ~/.zshrc — generated by WSL-Quick-ZSH. Plain zsh + plugins + starship.

# ---- History --------------------------------------------------------------
HISTFILE="${HOME}/.zsh_history"
HISTSIZE=50000
SAVEHIST=50000
setopt HIST_IGNORE_ALL_DUPS HIST_IGNORE_SPACE HIST_REDUCE_BLANKS
setopt SHARE_HISTORY INC_APPEND_HISTORY EXTENDED_HISTORY

# ---- Sane defaults --------------------------------------------------------
setopt AUTO_CD INTERACTIVE_COMMENTS NO_BEEP

PLUGIN_DIR="${HOME}/.zsh/plugins"

# ---- zsh-completions: fpath only (do NOT source); must precede compinit ----
fpath=("${PLUGIN_DIR}/zsh-completions/src" $fpath)

# ---- Completion system ----------------------------------------------------
autoload -Uz compinit
if [[ -n ${ZDOTDIR:-$HOME}/.zcompdump(#qN.mh+24) ]]; then
  compinit
else
  compinit -C
fi
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*:descriptions' format '[%d]'

# ---- Plugins (order matters) ----------------------------------------------
source "${PLUGIN_DIR}/zsh-autosuggestions/zsh-autosuggestions.zsh"
ZSH_AUTOSUGGEST_STRATEGY=(history completion)

export YSU_MESSAGE_POSITION="after"
source "${PLUGIN_DIR}/zsh-you-should-use/you-should-use.plugin.zsh"

# syntax-highlighting must be near the END
source "${PLUGIN_DIR}/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

# history-substring-search must come AFTER syntax-highlighting
source "${PLUGIN_DIR}/zsh-history-substring-search/zsh-history-substring-search.zsh"
bindkey "${terminfo[kcuu1]:-^[[A}" history-substring-search-up
bindkey "${terminfo[kcud1]:-^[[B}" history-substring-search-down
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# ---- Listing aliases (eza if present, else coloured coreutils ls) ---------
if command -v eza >/dev/null 2>&1; then
  alias ls='eza --group-directories-first'
  alias ll='eza -l --group-directories-first --git'
  alias la='eza -la --group-directories-first --git'
  alias lt='eza --tree --level=2 --group-directories-first'
else
  alias ls='ls --color=auto --group-directories-first'
  alias ll='ls -lh --color=auto --group-directories-first'
  alias la='ls -lAh --color=auto --group-directories-first'
fi

# ---- Prompt ---------------------------------------------------------------
command -v starship >/dev/null 2>&1 && eval "$(starship init zsh)"
ZSHRC
c_ok "Wrote ~/.zshrc"

# --- ~/.config/starship.toml ---
mkdir -p "${HOME}/.config"
backup "${HOME}/.config/starship.toml"
cat > "${HOME}/.config/starship.toml" <<'STARSHIP'
# ~/.config/starship.toml — "simplest bling"
add_newline = true
command_timeout = 1000

format = """
$directory\
$git_branch\
$git_status\
$character"""

[directory]
style = "bold cyan"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = " "
style = "bold purple"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold yellow"
format = "([$all_status$ahead_behind]($style)) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"
STARSHIP
c_ok "Wrote ~/.config/starship.toml"

# ---- 5. default shell ------------------------------------------------------
zsh_path="$(command -v zsh)"
if [ "${SHELL:-}" != "$zsh_path" ]; then
  c_info "Setting zsh as your default login shell..."
  if chsh -s "$zsh_path"; then
    c_ok "Default shell set to zsh (takes effect on next login)."
  else
    c_warn "chsh failed. Set it manually:  chsh -s $zsh_path"
  fi
else
  c_ok "zsh is already your default shell."
fi

echo
c_ok "Done! Start zsh now with:  exec zsh"
